GET http://localhost:3000/all-movies

###
POST http://localhost:3000/create-movie
Content-Type: application/json

{
  "titulo": "Capitão América: Guerra Civil",
  "genero": "Ação",
  "duracao": 147,
  "classificacao": "12 anos"
}

###
DELETE http://localhost:3000/delete-movie/1

###
PUT http://localhost:3000/update-movie/1
Content-Type: application/json

{
    "titulo": "Homem-Aranha",
    "genero": "Ação",
    "duracao": 121,
    "classificacao": "12 anos"
}