
GET http://localhost:3000/all-movies
###
POST http://localhost:3000/create-filmes
Content-Type: application/json

{
    "titulo": "WALL-E",
    "diretor": "Andrew Stanton",
    "genero": "Animação / Ficção Científica / Família",
    "duracao": "98 min (1h 38min)",
    "classificacao_etaria": "Livre"
}
###
DELETE http://localhost:3000/delete-filmes/9
###
PUT http://localhost:3000/update-filmes/12
Content-Type: application/json

{
    "titulo": "Titanicnic",
    "diretor": "James Camarao",
    "genero": "Drama / Terror/ Romance",
    "duracao": "194 min (3h 14min)",
    "classificacao_etaria": "19 anos"
    
    }